using Microsoft.EntityFrameworkCore;

namespace Api.Modules.Animals;

public static class AnimalSeeder
{
    public static async Task SeedAsync(AnimalDbContext db)
    {
        if (await db.Animals.AnyAsync())
            return;

        var animals = new List<Animal>
        {
            new() { Name = "Leo",       Species = "Lion",           Age = 5  },
            new() { Name = "Nala",      Species = "Lion",           Age = 4  },
            new() { Name = "Dumbo",     Species = "Elephant",       Age = 12 },
            new() { Name = "Babar",     Species = "Elephant",       Age = 20 },
            new() { Name = "Flipper",   Species = "Dolphin",        Age = 7  },
            new() { Name = "Shamu",     Species = "Orca",           Age = 15 },
            new() { Name = "Simba",     Species = "Lion",           Age = 3  },
            new() { Name = "Mufasa",    Species = "Lion",           Age = 10 },
            new() { Name = "Zara",      Species = "Zebra",          Age = 6  },
            new() { Name = "Stripes",   Species = "Zebra",          Age = 8  },
            new() { Name = "Spot",      Species = "Cheetah",        Age = 4  },
            new() { Name = "Cheetara",  Species = "Cheetah",        Age = 5  },
            new() { Name = "Koko",      Species = "Gorilla",        Age = 22 },
            new() { Name = "Bobo",      Species = "Gorilla",        Age = 14 },
            new() { Name = "Panda",     Species = "Giant Panda",    Age = 9  },
            new() { Name = "Mei Mei",   Species = "Giant Panda",    Age = 7  },
            new() { Name = "Rafiki",    Species = "Mandrill",       Age = 11 },
            new() { Name = "Timon",     Species = "Meerkat",        Age = 3  },
            new() { Name = "Pumba",     Species = "Warthog",        Age = 5  },
            new() { Name = "Alex",      Species = "Lion",           Age = 6  },
            new() { Name = "Marty",     Species = "Zebra",          Age = 7  },
            new() { Name = "Gloria",    Species = "Hippopotamus",   Age = 13 },
            new() { Name = "Melman",    Species = "Giraffe",        Age = 9  },
            new() { Name = "Skipper",   Species = "Penguin",        Age = 4  },
            new() { Name = "Kowalski",  Species = "Penguin",        Age = 4  },
            new() { Name = "Rico",      Species = "Penguin",        Age = 4  },
            new() { Name = "Private",   Species = "Penguin",        Age = 2  },
            new() { Name = "Gia",       Species = "Jaguar",         Age = 6  },
            new() { Name = "Vitaly",    Species = "Tiger",          Age = 8  },
            new() { Name = "Stefano",   Species = "Sea Lion",       Age = 5  },
            new() { Name = "Giraffy",   Species = "Giraffe",        Age = 11 },
            new() { Name = "Rhino",     Species = "Rhinoceros",     Age = 16 },
            new() { Name = "Hippo",     Species = "Hippopotamus",   Age = 10 },
            new() { Name = "Croc",      Species = "Crocodile",      Age = 30 },
            new() { Name = "Snap",      Species = "Crocodile",      Age = 25 },
            new() { Name = "Polly",     Species = "Parrot",         Age = 18 },
            new() { Name = "Tweety",    Species = "Canary",         Age = 2  },
            new() { Name = "Blu",       Species = "Macaw",          Age = 6  },
            new() { Name = "Jewel",     Species = "Macaw",          Age = 5  },
            new() { Name = "Zazu",      Species = "Hornbill",       Age = 7  },
            new() { Name = "Iago",      Species = "Parrot",         Age = 12 },
            new() { Name = "Falcon",    Species = "Peregrine Falcon", Age = 3 },
            new() { Name = "Eagle",     Species = "Bald Eagle",     Age = 8  },
            new() { Name = "Hoot",      Species = "Barn Owl",       Age = 4  },
            new() { Name = "Hedwig",    Species = "Snowy Owl",      Age = 5  },
            new() { Name = "Nemo",      Species = "Clownfish",      Age = 1  },
            new() { Name = "Dory",      Species = "Blue Tang",      Age = 2  },
            new() { Name = "Bruce",     Species = "Great White Shark", Age = 14 },
            new() { Name = "Crush",     Species = "Sea Turtle",     Age = 150 },
            new() { Name = "Squirt",    Species = "Sea Turtle",     Age = 5  },
            new() { Name = "Sebastian", Species = "Crab",           Age = 3  },
            new() { Name = "Flounder",  Species = "Tropical Fish",  Age = 2  },
            new() { Name = "Tigger",    Species = "Tiger",          Age = 5  },
            new() { Name = "Shere Khan", Species = "Tiger",         Age = 10 },
            new() { Name = "Baloo",     Species = "Brown Bear",     Age = 9  },
            new() { Name = "Paddington", Species = "Brown Bear",    Age = 4  },
            new() { Name = "Yogi",      Species = "Brown Bear",     Age = 7  },
            new() { Name = "Fozzie",    Species = "Brown Bear",     Age = 6  },
            new() { Name = "Polar",     Species = "Polar Bear",     Age = 8  },
            new() { Name = "Nanuk",     Species = "Polar Bear",     Age = 12 },
            new() { Name = "Skippy",    Species = "Kangaroo",       Age = 4  },
            new() { Name = "Roo",       Species = "Kangaroo",       Age = 2  },
            new() { Name = "Kanga",     Species = "Kangaroo",       Age = 5  },
            new() { Name = "Koala",     Species = "Koala",          Age = 6  },
            new() { Name = "Wombat",    Species = "Wombat",         Age = 3  },
            new() { Name = "Dingo",     Species = "Dingo",          Age = 4  },
            new() { Name = "Wolfy",     Species = "Gray Wolf",      Age = 7  },
            new() { Name = "Balto",     Species = "Gray Wolf",      Age = 5  },
            new() { Name = "Foxie",     Species = "Red Fox",        Age = 3  },
            new() { Name = "Nick",      Species = "Red Fox",        Age = 4  },
            new() { Name = "Judy",      Species = "Rabbit",         Age = 2  },
            new() { Name = "Thumper",   Species = "Rabbit",         Age = 1  },
            new() { Name = "Bambi",     Species = "White-tailed Deer", Age = 2 },
            new() { Name = "Faline",    Species = "White-tailed Deer", Age = 2 },
            new() { Name = "Rudolph",   Species = "Reindeer",       Age = 5  },
            new() { Name = "Prancer",   Species = "Reindeer",       Age = 6  },
            new() { Name = "Moose",     Species = "Moose",          Age = 8  },
            new() { Name = "Bison",     Species = "American Bison", Age = 10 },
            new() { Name = "Stallion",  Species = "Horse",          Age = 7  },
            new() { Name = "Spirit",    Species = "Horse",          Age = 6  },
            new() { Name = "Zebedee",   Species = "Zebra",          Age = 5  },
            new() { Name = "Camela",    Species = "Camel",          Age = 14 },
            new() { Name = "Hump",      Species = "Camel",          Age = 11 },
            new() { Name = "Llama",     Species = "Llama",          Age = 8  },
            new() { Name = "Alpaca",    Species = "Alpaca",         Age = 5  },
            new() { Name = "Cleo",      Species = "Chimpanzee",     Age = 12 },
            new() { Name = "Darwin",    Species = "Chimpanzee",     Age = 9  },
            new() { Name = "Kong",      Species = "Gorilla",        Age = 18 },
            new() { Name = "Gibby",     Species = "Gibbon",         Age = 7  },
            new() { Name = "Lemmy",     Species = "Ring-tailed Lemur", Age = 6 },
            new() { Name = "Sifaka",    Species = "Sifaka",         Age = 4  },
            new() { Name = "Mamba",     Species = "Black Mamba",    Age = 5  },
            new() { Name = "Cobra",     Species = "King Cobra",     Age = 8  },
            new() { Name = "Tortoise",  Species = "Aldabra Tortoise", Age = 75 },
            new() { Name = "Iggy",      Species = "Green Iguana",   Age = 6  },
            new() { Name = "Gecko",     Species = "Leopard Gecko",  Age = 3  },
            new() { Name = "Chameleon", Species = "Veiled Chameleon", Age = 2 },
            new() { Name = "Axolotl",   Species = "Axolotl",        Age = 4  },
        };

        db.Animals.AddRange(animals);
        await db.SaveChangesAsync();
    }
}
