/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesheetsIndexRouteImport } from './routes/timesheets/index'
import { Route as TimeEntryIndexRouteImport } from './routes/time-entry/index'
import { Route as LeaveOverviewIndexRouteImport } from './routes/leave-overview/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminLeaveTypesIndexRouteImport } from './routes/admin/leave-types/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminContractsIndexRouteImport } from './routes/admin/contracts/index'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as AdminLeaveTypesNewRouteImport } from './routes/admin/leave-types/new'
import { Route as AdminLeaveTypesIdRouteImport } from './routes/admin/leave-types/$id'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers/new'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'
import { Route as AdminContractsNewRouteImport } from './routes/admin/contracts/new'
import { Route as AdminContractsIdRouteImport } from './routes/admin/contracts/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetsIndexRoute = TimesheetsIndexRouteImport.update({
  id: '/timesheets/',
  path: '/timesheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeEntryIndexRoute = TimeEntryIndexRouteImport.update({
  id: '/time-entry/',
  path: '/time-entry/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveOverviewIndexRoute = LeaveOverviewIndexRouteImport.update({
  id: '/leave-overview/',
  path: '/leave-overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaveTypesIndexRoute = AdminLeaveTypesIndexRouteImport.update({
  id: '/admin/leave-types/',
  path: '/admin/leave-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsIndexRoute = AdminContractsIndexRouteImport.update({
  id: '/admin/contracts/',
  path: '/admin/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaveTypesNewRoute = AdminLeaveTypesNewRouteImport.update({
  id: '/admin/leave-types/new',
  path: '/admin/leave-types/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaveTypesIdRoute = AdminLeaveTypesIdRouteImport.update({
  id: '/admin/leave-types/$id',
  path: '/admin/leave-types/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/admin/customers/new',
  path: '/admin/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/admin/customers/$id',
  path: '/admin/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsNewRoute = AdminContractsNewRouteImport.update({
  id: '/admin/contracts/new',
  path: '/admin/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsIdRoute = AdminContractsIdRouteImport.update({
  id: '/admin/contracts/$id',
  path: '/admin/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/leave-overview/': typeof LeaveOverviewIndexRoute
  '/time-entry/': typeof TimeEntryIndexRoute
  '/timesheets/': typeof TimesheetsIndexRoute
  '/admin/contracts/$id': typeof AdminContractsIdRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/leave-types/$id': typeof AdminLeaveTypesIdRoute
  '/admin/leave-types/new': typeof AdminLeaveTypesNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/leave-types/': typeof AdminLeaveTypesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/leave-overview': typeof LeaveOverviewIndexRoute
  '/time-entry': typeof TimeEntryIndexRoute
  '/timesheets': typeof TimesheetsIndexRoute
  '/admin/contracts/$id': typeof AdminContractsIdRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/leave-types/$id': typeof AdminLeaveTypesIdRoute
  '/admin/leave-types/new': typeof AdminLeaveTypesNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/contracts': typeof AdminContractsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/leave-types': typeof AdminLeaveTypesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/leave-overview/': typeof LeaveOverviewIndexRoute
  '/time-entry/': typeof TimeEntryIndexRoute
  '/timesheets/': typeof TimesheetsIndexRoute
  '/admin/contracts/$id': typeof AdminContractsIdRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/leave-types/$id': typeof AdminLeaveTypesIdRoute
  '/admin/leave-types/new': typeof AdminLeaveTypesNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/leave-types/': typeof AdminLeaveTypesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/leave-overview/'
    | '/time-entry/'
    | '/timesheets/'
    | '/admin/contracts/$id'
    | '/admin/contracts/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/leave-types/$id'
    | '/admin/leave-types/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/contracts/'
    | '/admin/customers/'
    | '/admin/leave-types/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/leave-overview'
    | '/time-entry'
    | '/timesheets'
    | '/admin/contracts/$id'
    | '/admin/contracts/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/leave-types/$id'
    | '/admin/leave-types/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/contracts'
    | '/admin/customers'
    | '/admin/leave-types'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/leave-overview/'
    | '/time-entry/'
    | '/timesheets/'
    | '/admin/contracts/$id'
    | '/admin/contracts/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/leave-types/$id'
    | '/admin/leave-types/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/contracts/'
    | '/admin/customers/'
    | '/admin/leave-types/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LeaveOverviewIndexRoute: typeof LeaveOverviewIndexRoute
  TimeEntryIndexRoute: typeof TimeEntryIndexRoute
  TimesheetsIndexRoute: typeof TimesheetsIndexRoute
  AdminContractsIdRoute: typeof AdminContractsIdRoute
  AdminContractsNewRoute: typeof AdminContractsNewRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminLeaveTypesIdRoute: typeof AdminLeaveTypesIdRoute
  AdminLeaveTypesNewRoute: typeof AdminLeaveTypesNewRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminContractsIndexRoute: typeof AdminContractsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminLeaveTypesIndexRoute: typeof AdminLeaveTypesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets/': {
      id: '/timesheets/'
      path: '/timesheets'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof TimesheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-entry/': {
      id: '/time-entry/'
      path: '/time-entry'
      fullPath: '/time-entry/'
      preLoaderRoute: typeof TimeEntryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-overview/': {
      id: '/leave-overview/'
      path: '/leave-overview'
      fullPath: '/leave-overview/'
      preLoaderRoute: typeof LeaveOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leave-types/': {
      id: '/admin/leave-types/'
      path: '/admin/leave-types'
      fullPath: '/admin/leave-types/'
      preLoaderRoute: typeof AdminLeaveTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts/': {
      id: '/admin/contracts/'
      path: '/admin/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AdminContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leave-types/new': {
      id: '/admin/leave-types/new'
      path: '/admin/leave-types/new'
      fullPath: '/admin/leave-types/new'
      preLoaderRoute: typeof AdminLeaveTypesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leave-types/$id': {
      id: '/admin/leave-types/$id'
      path: '/admin/leave-types/$id'
      fullPath: '/admin/leave-types/$id'
      preLoaderRoute: typeof AdminLeaveTypesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/admin/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/admin/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts/new': {
      id: '/admin/contracts/new'
      path: '/admin/contracts/new'
      fullPath: '/admin/contracts/new'
      preLoaderRoute: typeof AdminContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts/$id': {
      id: '/admin/contracts/$id'
      path: '/admin/contracts/$id'
      fullPath: '/admin/contracts/$id'
      preLoaderRoute: typeof AdminContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  LeaveOverviewIndexRoute: LeaveOverviewIndexRoute,
  TimeEntryIndexRoute: TimeEntryIndexRoute,
  TimesheetsIndexRoute: TimesheetsIndexRoute,
  AdminContractsIdRoute: AdminContractsIdRoute,
  AdminContractsNewRoute: AdminContractsNewRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminLeaveTypesIdRoute: AdminLeaveTypesIdRoute,
  AdminLeaveTypesNewRoute: AdminLeaveTypesNewRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminContractsIndexRoute: AdminContractsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminLeaveTypesIndexRoute: AdminLeaveTypesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
